### ISSUE TITLE
Remove misspelled and misplaced parameter.

### ISSUE THREAD

**Issue by danielballan** [oksanagit/deployAD#1]
This parameter is misspelled and misplaced. (It's under `vars`, when it looks like was intended to be passed to the module as a [`force_apt_get` parameter](https://docs.ansible.com/ansible/latest/modules/apt_module.html#parameter-force_apt_get)). Assuming that the role works anyway, that probably means it can be removed.

Example:

https://github.com/oksanagit/deployAD/blob/1696a29ab33f3f8c71501448e23d347433b91b96/roles/install_system_packages/tasks/Debian.yml#L25

It occurs in three places total:

```
$ git grep forse_apt_get
roles/ADEiger/tasks/main.yml:      forse_apt_get: yes
roles/ADProsilica/tasks/main.yml:#       forse_apt_get: yes
roles/Debian/tasks/main.yml:      forse_apt_get: yes
```

**Comment by danielballan** [comment]
I grepped on an out-of-date checkout. It occurs in _two_ places total now:

```
roles/ADEiger/tasks/main.yml:      forse_apt_get: yes
roles/install_system_packages/tasks/Debian.yml:      forse_apt_get: yes
```

**Comment by oksanagit** [comment]
I have removed this misspelled and unused variable in both places.
